#!/usr/bin/env bash
# =============================================================================
# run_analysis.sh — __STUDY_LABEL__ bundle — HPC cluster launcher
#
# Use this script to launch the analysis on the HPC cluster instead of calling
# Rscript directly.  It sets the required environment variables in the shell
# BEFORE R starts, which is necessary for libjvm.so to be found.
#
# USAGE:
#   bash run_analysis.sh
#
# PREREQUISITES (run once per session before this script):
#   bash setup_env.sh     # creates conda env + obtains Kerberos ticket
#
# WHY A WRAPPER SCRIPT:
#   rJava loads libjvm.so via dyn.load() when library(rJava) is called.
#   The OS dynamic linker resolves shared libraries using LD_LIBRARY_PATH
#   from the shell environment that launched R — setting it inside R with
#   Sys.setenv() is not reliable because the linker may have already cached
#   the search path at process start.
# =============================================================================

set -euo pipefail

BUNDLE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$BUNDLE_DIR"

# ---------------------------------------------------------------------------
# Load site-specific .env (generated by step 9 with INST_OMOP_* values).
# Sets OMOP_SERVER, OMOP_DATABASE, OMOP_SPN_HOST, schemas, etc. so that
# config.R can read them via Sys.getenv() without manual editing.
# ---------------------------------------------------------------------------
if [[ -f "$BUNDLE_DIR/.env" ]]; then
  set -o allexport
  # shellcheck source=/dev/null
  source "$BUNDLE_DIR/.env"
  set +o allexport
fi

echo ""
echo "======================================================================"
echo "  __STUDY_LABEL__ — Analysis Launcher"
echo "  Bundle: $BUNDLE_DIR"
echo "======================================================================"
echo ""

# -----------------------------------------------------------------------------
# Step 1 — Activate conda environment
# -----------------------------------------------------------------------------
echo "[1/4] Activating conda environment ..."

module load miniforge
conda activate openjdk

if [[ -z "${JAVA_HOME:-}" ]]; then
  echo "ERROR: JAVA_HOME is not set after conda activate openjdk."
  echo "       Try running: bash setup_env.sh"
  exit 1
fi

echo "      JAVA_HOME: $JAVA_HOME"

# -----------------------------------------------------------------------------
# Step 2 — Set Kerberos ticket cache and verify ticket is valid
#
# KRB5CCNAME must be set in the shell before R starts — the JDBC driver
# reads it at connection time.  Set it here unconditionally so this script
# is self-contained (a new terminal will not inherit it from setup_env.sh).
# -----------------------------------------------------------------------------
echo "[2/4] Setting Kerberos ticket cache ..."

export KRB5CCNAME=FILE:~/krb5cc_java

if ! klist -s 2>/dev/null; then
  echo ""
  echo "ERROR: No valid Kerberos ticket found."
  echo "       Obtain a ticket first, then re-run this script:"
  echo "         export KRB5CCNAME=FILE:~/krb5cc_java && kinit"
  exit 1
fi

EXPIRY=$(klist 2>&1 | awk '/Expires/{found=1; next} found{print $1, $2; exit}')
echo "      KRB5CCNAME: $KRB5CCNAME"
echo "      Ticket valid. Expires: ${EXPIRY:-unknown}"
echo ""

# -----------------------------------------------------------------------------
# Step 3 — Find libjvm.so and set LD_LIBRARY_PATH before R starts
#
# Its exact path inside the conda JDK varies by platform/version, so we
# use `find` rather than hardcoding it.
# -----------------------------------------------------------------------------
echo "[3/4] Locating libjvm.so and configuring library paths ..."

JVM_LIB=$(find "${CONDA_PREFIX}" -name "libjvm.so" 2>/dev/null | head -1)

if [[ -z "$JVM_LIB" ]]; then
  JVM_LIB=$(find "${JAVA_HOME}" -name "libjvm.so" 2>/dev/null | head -1)
fi

if [[ -z "$JVM_LIB" ]]; then
  echo ""
  echo "ERROR: libjvm.so not found anywhere under CONDA_PREFIX or JAVA_HOME."
  echo "       CONDA_PREFIX = ${CONDA_PREFIX}"
  echo "       JAVA_HOME    = ${JAVA_HOME}"
  echo "       Try: conda install -n openjdk conda-forge::openjdk --force-reinstall"
  exit 1
fi

JVM_LIB_DIR="$(dirname "$JVM_LIB")"
echo "      libjvm.so found: $JVM_LIB"

export LD_LIBRARY_PATH="${JVM_LIB_DIR}:${CONDA_PREFIX}/lib:${LD_LIBRARY_PATH:-}"
echo "      LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}"
echo ""

# -----------------------------------------------------------------------------
# Step 4 — Launch the analysis
# -----------------------------------------------------------------------------
echo "[4/4] Launching analysis ..."
echo ""

Rscript run_analysis.R

echo ""
echo "======================================================================"
echo "  Analysis complete."
echo "  Output: $BUNDLE_DIR/output/risk_score_eval/"
echo "======================================================================"
