# =============================================================================
# config.R
# Central configuration for your OMOP study.
#
# This file reads study_params.yaml and merges it with infrastructure defaults
# (JDBC, Java, SQL Server connection) to produce a single named list consumed
# by all workflow steps.
#
# DO NOT edit this file for study-specific settings.
# Edit study_params.yaml instead.
#
# Infrastructure settings (JDBC, Java, SQL Server connection) are pre-wired
# for the dev container and typically do not need changes.
# =============================================================================

get_validation_config <- function() {

  # ---------------------------------------------------------------------------
  # Load study parameters from study_params.yaml.
  # ---------------------------------------------------------------------------
  if (!requireNamespace("yaml", quietly = TRUE)) {
    stop("Package 'yaml' is required. Install with: renv::install('yaml')")
  }

  params_file <- file.path(getwd(), "study_params.yaml")
  if (!file.exists(params_file)) {
    stop(
      "study_params.yaml not found.\n",
      "  Run: Rscript scripts/new_study.R <study_name>  to create it.\n",
      "  Or copy study_params.yaml.example to study_params.yaml and fill it in."
    )
  }

  p <- yaml::read_yaml(params_file)

  # Helper: return y when x is NULL.
  `%||%` <- function(x, y) if (is.null(x)) y else x

  # ---------------------------------------------------------------------------
  # JDBC / Java setup — self-contained under this project's drivers/ folder.
  # java_home is read from the JAVA_HOME env var (set in the dev container);
  # falls back to the Windows path for legacy Windows runs outside the container.
  # ---------------------------------------------------------------------------
  java_home        <- Sys.getenv("JAVA_HOME",
                        unset = "C:/Program Files/Eclipse Adoptium/jdk-17.0.18.8-hotspot")
  sql_server_jdbc_version <- "13.2.1"
  path_to_driver   <- file.path(getwd(), "drivers")
  jdbc_home        <- file.path(path_to_driver, "sqljdbc_13.2", "enu")
  jdbc_runtime_dir <- file.path(path_to_driver, "jdbc-runtime")

  # Bracket-quote a SQL Server identifier that contains characters requiring
  # quoting (backslash, space, hyphen, dot).  Applied to results_schema once at
  # config creation so that every consumer of config$results_schema is safe to
  # use the value directly in SQL — no call-site quoting needed.
  .bq <- function(x) {
    if (nchar(x) > 0 && grepl("[\\\\\\s\\-\\.]", x, perl = TRUE) &&
        !grepl("^\\[", x))
      paste0("[", x, "]")
    else x
  }

  # Slugify a study_name into a SQL-Server-safe identifier stem: lowercase,
  # with hyphens / dots / whitespace collapsed to single underscores.  Used to
  # derive default results_schema and output_folder names from
  # study_name when those fields are omitted from study_params.yaml.
  .slugify <- function(x) {
    s <- tolower(x)
    s <- gsub("[\\s\\-\\.]+", "_", s, perl = TRUE)
    s <- gsub("_+", "_", s)
    sub("^_|_$", "", s)
  }

  study_name_value <- p$study_name %||% "my_study"
  study_slug       <- .slugify(study_name_value)

  list(

    # -------------------------------------------------------------------------
    # Java / JDBC
    # -------------------------------------------------------------------------
    java_home               = java_home,
    java_bin                = file.path(java_home, "bin"),
    sql_server_jdbc_version = sql_server_jdbc_version,
    jdbc_zip_url            = "https://go.microsoft.com/fwlink/?linkid=2338346&clcid=0x409",
    path_to_driver          = path_to_driver,
    jdbc_home               = jdbc_home,
    jdbc_jar_folder         = file.path(jdbc_home, "jars"),
    jdbc_runtime_dir        = jdbc_runtime_dir,
    jdbc_auth_dir           = file.path(jdbc_home, "auth", "x64"),

    # -------------------------------------------------------------------------
    # SQL Server connection
    # MSSQL_HOST defaults to localhost (macOS/Windows direct); set to mssql_dev
    # inside the dev container via the MSSQL_HOST environment variable.
    # -------------------------------------------------------------------------
    dbms             = "sql server",
    server           = Sys.getenv("MSSQL_HOST", unset = "localhost"),
    user             = "SA",
    password         = Sys.getenv("MSSQL_SA_PASSWORD", unset = "P@ssw0rd!"),
    database         = "omop_synth",
    sql_server_port  = 1433L,

    # Shared vocabulary schema — loaded once via
    # infrastructure/scripts/setup_omop_vocab_schema.R --study-dir synthea-omop-template
    vocab_schema     = "omop_vocab",

    # -------------------------------------------------------------------------
    # Study identity — from study_params.yaml
    # -------------------------------------------------------------------------
    study_name   = study_name_value,

    # -------------------------------------------------------------------------
    # Database schemas — from study_params.yaml.
    # results_schema auto-derives from study_name (via study_slug) when omitted; cdm_schema must be set explicitly because the
    # CDM is typically a shared dataset populated by a separate ETL.
    # -------------------------------------------------------------------------
    cdm_schema        = p$cdm_schema     %||% "cdm_my_study",
    cdm_version       = 5L,
    results_schema    = .bq(p$results_schema %||% paste0(study_slug, "_results")),

    # -------------------------------------------------------------------------
    # Output folders — from study_params.yaml.
    # output_folder:          generation and QC outputs
    # achilles_output_folder: CDM-level ACHILLES profiling (workflow 06)
    # dqd_output_folder:      CDM-level Data Quality Dashboard (workflow 06)
    #
    # All three are runtime-only and excluded from git via .gitignore (output/).
    # QC outputs are nested under output/qc/ to keep them separate from generation
    # outputs while avoiding a new root-level directory.
    # -------------------------------------------------------------------------
    output_folder          = file.path(getwd(), p$output_folder %||% "output"),
    achilles_output_folder = file.path(getwd(), "output", "qc", "achilles"),
    dqd_output_folder      = file.path(getwd(), "output", "qc", "dqd"),

    # -------------------------------------------------------------------------
    # Database metadata — from study_params.yaml
    # -------------------------------------------------------------------------
    cdm_database_id          = p$cdm_database_id          %||% "my_cdm_v5.4",
    cdm_database_name        = p$cdm_database_name        %||% "My Study Database",
    cdm_database_description = p$cdm_database_description %||%
                                 "Brief description of the patient population."
  )
}
