# =============================================================================
# config.R
# Central configuration for your OMOP study.
#
# This file reads study_params.yaml and merges it with infrastructure defaults
# (JDBC, Java, SQL Server connection) to produce a single named list consumed
# by all workflow steps.
#
# DO NOT edit this file for study-specific settings.
# Edit study_params.yaml instead.
#
# Infrastructure settings (JDBC, Java, SQL Server connection) are pre-wired
# for the dev container and typically do not need changes.
# =============================================================================

get_validation_config <- function() {

  # ---------------------------------------------------------------------------
  # Load study parameters from study_params.yaml.
  # ---------------------------------------------------------------------------
  if (!requireNamespace("yaml", quietly = TRUE)) {
    stop("Package 'yaml' is required. Install with: renv::install('yaml')")
  }

  params_file <- file.path(getwd(), "study_params.yaml")
  if (!file.exists(params_file)) {
    stop(
      "study_params.yaml not found.\n",
      "  Run: Rscript scripts/new_study.R <study_name>  to create it.\n",
      "  Or copy study_params.yaml.example to study_params.yaml and fill it in."
    )
  }

  p <- yaml::read_yaml(params_file)

  # Helper: coerce a YAML value (may be NULL / list / scalar) to integer vector.
  # Returns integer(0) when the YAML field is null or an empty sequence [].
  as_int_vec <- function(x) {
    if (is.null(x)) return(integer(0))
    v <- suppressWarnings(as.integer(unlist(x)))
    v[!is.na(v)]
  }

  # Helper: return y when x is NULL.
  `%||%` <- function(x, y) if (is.null(x)) y else x

  # ---------------------------------------------------------------------------
  # JDBC / Java setup — self-contained under this project's drivers/ folder.
  # java_home is read from the JAVA_HOME env var (set in the dev container);
  # falls back to the Windows path for legacy Windows runs outside the container.
  # ---------------------------------------------------------------------------
  java_home        <- Sys.getenv("JAVA_HOME",
                        unset = "C:/Program Files/Eclipse Adoptium/jdk-17.0.18.8-hotspot")
  sql_server_jdbc_version <- "13.2.1"
  path_to_driver   <- file.path(getwd(), "drivers")
  jdbc_home        <- file.path(path_to_driver, "sqljdbc_13.2", "enu")
  jdbc_runtime_dir <- file.path(path_to_driver, "jdbc-runtime")

  list(

    # -------------------------------------------------------------------------
    # Java / JDBC
    # -------------------------------------------------------------------------
    java_home               = java_home,
    java_bin                = file.path(java_home, "bin"),
    sql_server_jdbc_version = sql_server_jdbc_version,
    jdbc_zip_url            = "https://go.microsoft.com/fwlink/?linkid=2338346&clcid=0x409",
    path_to_driver          = path_to_driver,
    jdbc_home               = jdbc_home,
    jdbc_jar_folder         = file.path(jdbc_home, "jars"),
    jdbc_runtime_dir        = jdbc_runtime_dir,
    jdbc_auth_dir           = file.path(jdbc_home, "auth", "x64"),

    # -------------------------------------------------------------------------
    # SQL Server connection
    # MSSQL_HOST defaults to localhost (macOS/Windows direct); set to mssql_dev
    # inside the dev container via the MSSQL_HOST environment variable.
    # -------------------------------------------------------------------------
    dbms             = "sql server",
    server           = Sys.getenv("MSSQL_HOST", unset = "localhost"),
    user             = "SA",
    password         = Sys.getenv("MSSQL_SA_PASSWORD", unset = "P@ssw0rd!"),
    database         = "omop_synth",
    sql_server_port  = 1433L,

    # Shared vocabulary schema — loaded once via
    # ../infrastructure/scripts/setup_omop_vocab_schema.R --study-dir .
    vocab_schema     = "omop_vocab",

    # -------------------------------------------------------------------------
    # Study identity — from study_params.yaml
    # -------------------------------------------------------------------------
    study_name   = p$study_name   %||% "my_study",
    study_design = p$study_design %||% "prognostic_model",

    # -------------------------------------------------------------------------
    # Database schemas — from study_params.yaml
    # -------------------------------------------------------------------------
    cdm_schema        = p$cdm_schema     %||% "cdm_my_study",
    cdm_version       = 5L,
    results_schema    = p$results_schema %||% "my_study_results",
    results_database  = p$results_database %||% NA_character_,
    cohort_table      = p$cohort_table   %||% "my_study_cohort",

    # -------------------------------------------------------------------------
    # Cohort IDs — from study_params.yaml
    # -------------------------------------------------------------------------
    target_cohort_id     = as.integer(p$target$cohort_id %||% 1L),
    comparator_cohort_id = if (!is.null(p$comparator$cohort_id))
                             as.integer(p$comparator$cohort_id) else NA_integer_,
    outcome_cohort_id    = if (!is.null(p$outcome$cohort_id))
                             as.integer(p$outcome$cohort_id) else NA_integer_,

    # -------------------------------------------------------------------------
    # Cohort SQL file paths — from study_params.yaml
    # -------------------------------------------------------------------------
    target_cohort_sql     = p$target$sql_file     %||% "cohorts/target_surgery.sql",
    comparator_cohort_sql = p$comparator$sql_file %||% "cohorts/comparator_cohort.sql",
    outcome_cohort_sql    = p$outcome$sql_file,

    # -------------------------------------------------------------------------
    # Target cohort phenotype parameters — passed as SqlRender params at runtime
    # -------------------------------------------------------------------------
    target_visit_concept_ids    = as_int_vec(p$target$visit_concept_ids),
    target_min_age              = as.integer(p$target$min_age_at_index %||% 0L),
    target_index_concept_ids    = as_int_vec(p$target$index_event$ancestor_concept_ids),
    target_index_domain         = p$target$index_event$domain %||% "procedure",
    target_washout_concept_ids  = as_int_vec(p$target$washout$ancestor_concept_ids),
    target_washout_lookback_days = as.integer(
                                    p$target$washout$lookback_days %||% 365L),

    # -------------------------------------------------------------------------
    # Comparator cohort phenotype parameters — passed as SqlRender params at runtime.
    # These are only used when comparator.cohort_id is set in study_params.yaml.
    # -------------------------------------------------------------------------
    comparator_visit_concept_ids     = as_int_vec(p$comparator$visit_concept_ids),
    comparator_min_age               = as.integer(p$comparator$min_age_at_index %||% 0L),
    comparator_index_concept_ids     = as_int_vec(p$comparator$index_event$ancestor_concept_ids),
    comparator_index_domain          = p$comparator$index_event$domain %||% "procedure",
    comparator_washout_concept_ids   = as_int_vec(p$comparator$washout$ancestor_concept_ids),
    comparator_washout_lookback_days = as.integer(
                                         p$comparator$washout$lookback_days %||% 365L),

    # -------------------------------------------------------------------------
    # Outcome cohort phenotype parameters
    # -------------------------------------------------------------------------
    outcome_concept_ids = as_int_vec(p$outcome$ancestor_concept_ids),

    # -------------------------------------------------------------------------
    # Existing ATLAS cohorts (optional).
    # If use_atlas_cohorts = TRUE the target cohort is copied from ATLAS.
    # -------------------------------------------------------------------------
    use_atlas_cohorts       = FALSE,
    atlas_cohort_schema     = "results",
    atlas_cohort_table      = "cohort",
    atlas_target_cohort_id  = NA_integer_,
    atlas_outcome_cohort_id = NA_integer_,

    # -------------------------------------------------------------------------
    # Covariate / feature definition files (pre-specified covariate list).
    # Used when you have a version-controlled, protocol-specified set of
    # covariates rather than automated FeatureExtraction across all domains.
    # Set either to NULL in workflow/08 to skip this pipeline and use
    # FeatureExtraction::createCovariateSettings() directly instead.
    # -------------------------------------------------------------------------
    covariate_definitions_file = file.path("covariates", "covariates.csv"),
    covariate_concepts_file    = file.path("covariates", "covariate_concepts.csv"),

    # -------------------------------------------------------------------------
    # Analysis parameters — from study_params.yaml
    # -------------------------------------------------------------------------
    prediction_window_days     = as.integer(p$prediction_window_days     %||% 90L),
    min_prior_observation_days = as.integer(p$min_prior_observation_days %||% 365L),
    covariate_lookback_days    = as.integer(p$covariate_lookback_days    %||% 365L),

    # -------------------------------------------------------------------------
    # Study date window — from study_params.yaml
    # -------------------------------------------------------------------------
    study_start_date = p$study_start_date %||% "2017-01-01",
    study_end_date   = p$study_end_date   %||% "2025-12-31",

    # -------------------------------------------------------------------------
    # Output folder — from study_params.yaml
    # -------------------------------------------------------------------------
    output_folder = file.path(getwd(),
                              p$output_folder %||% file.path("output", "my_study")),

    # -------------------------------------------------------------------------
    # Database metadata — from study_params.yaml
    # -------------------------------------------------------------------------
    cdm_database_id          = p$cdm_database_id          %||% "my_cdm_v5.4",
    cdm_database_name        = p$cdm_database_name        %||% "My Study Database",
    cdm_database_description = p$cdm_database_description %||%
                                 "Brief description of the patient population.",

    # -------------------------------------------------------------------------
    # Analysis flags — from study_params.yaml analyses: section.
    # These drive workflow/08 — no code editing in that script is needed.
    # -------------------------------------------------------------------------
    run_cohort_characterization = isTRUE(p$analyses$cohort_characterization),
    run_prognostic_model        = isTRUE(p$analyses$prognostic_model),
    run_causal_inference        = isTRUE(p$analyses$causal_inference),
    run_integer_risk_score      = isTRUE(p$analyses$integer_risk_score),
    run_word_report             = isTRUE(p$analyses$word_report)
  )
}
