setwd("C:/Users/rapiduser/pad-oler-ssi-val")
source("renv/activate.R")
source("config.R")
cfg <- get_validation_config()
java_bin <- file.path(cfg$java_home, "bin")
Sys.setenv(JAVA_HOME = cfg$java_home)
Sys.setenv(PATH = paste(normalizePath(java_bin, winslash = "/", mustWork = FALSE), Sys.getenv("PATH"), sep = .Platform$path.sep))
options(java.parameters = paste0("-Djava.home=", normalizePath(cfg$java_home, winslash = "/", mustWork = FALSE)))
source("scripts/etl/reset_omop_and_staging.R")
source("scripts/etl/run_synthea_csv_to_omop_etl.R")
run_synthea_csv_to_omop_etl(csv_input_dir = "C:/Users/rapiduser/source/repos/synthea/output/csv", run_name = "padssi-csv-20260324-refresh")
cat("STEP5_DIRECT_DONE\n")
