-- =============================================================================
-- cohorts/outcome_ssi.sql
-- OUTCOME COHORT — parameterized template
--
-- DO NOT EDIT THIS FILE directly. Set all study-specific values in
-- study_params.yaml under the "outcome:" section. Parameters are injected
-- at runtime by R/cohorts.R via SqlRender.
--
-- PARAMETERS (all injected from study_params.yaml via R/cohorts.R):
--   @cdm_database_schema      CDM schema (config$cdm_schema)
--   @target_database_schema   Results schema prefix (config$results_schema)
--   @target_cohort_table      Cohort table name (config$cohort_table)
--   @outcome_cohort_id        Cohort definition ID (outcome.cohort_id)
--   @study_start_date         Study start date (study_start_date)
--   @study_end_date           Study end date (study_end_date)
--   @outcome_concept_ids      Ancestor concept IDs for the outcome condition
--                             (outcome.ancestor_concept_ids)
--
-- COHORT LOGIC:
--   OUTCOME EVENT : first occurrence of a condition matching the outcome ancestor
--                   concept hierarchy, within the study window.
--   INDEX DATE    : condition_start_date of the first outcome event.
--   COHORT EXIT   : condition_end_date (or index + 1 day if null).
--   ONE ENTRY     : first outcome event per person (rn = 1).
--
-- INCIDENT vs. PREVALENT:
--   This SQL captures all outcome events in the study window regardless of
--   whether they occurred before or after the patient's index date. The
--   determination of whether an outcome is truly NEW (post-index) is applied
--   in Step 8 by PatientLevelPrediction or CohortMethod, which join this
--   table to the target cohort and filter to events after cohort_start_date.
--
-- TO ADAPT FOR OTHER DOMAINS:
--   Procedure-based: replace condition_occurrence with procedure_occurrence,
--     condition_start_date with procedure_date, condition_end_date with
--     DATEADD(DAY, 1, procedure_date), and condition_concept_id with
--     procedure_concept_id.
--   Readmission: replace condition_occurrence with visit_occurrence,
--     filter visit_concept_id = 9201 (Inpatient).
--   Measurement: replace with measurement table, add value_as_number filter.
-- =============================================================================

-- Guard: fires when outcome concept IDs still contain the placeholder value 0.
{@outcome_concept_ids == "0"} ? {
  RAISERROR(
    'SETUP REQUIRED - outcome_ssi.sql: outcome_concept_ids = 0 placeholder '
    'has not been replaced. Set outcome.ancestor_concept_ids in '
    'study_params.yaml and re-run. Use /concept-lookup to find verified concept IDs.',
    16, 1
  );
  RETURN;
}

DELETE FROM @target_database_schema.@target_cohort_table
WHERE cohort_definition_id = @outcome_cohort_id;

INSERT INTO @target_database_schema.@target_cohort_table (
  cohort_definition_id,
  subject_id,
  cohort_start_date,
  cohort_end_date
)
SELECT
  @outcome_cohort_id                               AS cohort_definition_id,
  first_outcome.person_id                          AS subject_id,
  first_outcome.condition_start_date               AS cohort_start_date,
  ISNULL(
    first_outcome.condition_end_date,
    DATEADD(DAY, 1, first_outcome.condition_start_date)
  )                                                AS cohort_end_date
FROM (
  SELECT
    co.person_id,
    CAST(co.condition_start_date AS DATE) AS condition_start_date,
    CAST(co.condition_end_date   AS DATE) AS condition_end_date,
    -- First occurrence per person. Remove the WHERE rn = 1 filter below to
    -- capture recurrent events (e.g. repeated infections, readmissions).
    ROW_NUMBER() OVER (
      PARTITION BY co.person_id
      ORDER BY co.condition_start_date
    ) AS rn
  FROM @cdm_database_schema.condition_occurrence co
  INNER JOIN @cdm_database_schema.concept_ancestor ca
    ON ca.descendant_concept_id = co.condition_concept_id
  WHERE
    -- Outcome ancestor concept IDs: set outcome.ancestor_concept_ids in study_params.yaml.
    -- All descendants are captured automatically via concept_ancestor rollup.
    ca.ancestor_concept_id IN (@outcome_concept_ids)

    AND co.condition_start_date >= CAST('@study_start_date' AS DATE)
    AND co.condition_start_date <= CAST('@study_end_date'   AS DATE)

) first_outcome
WHERE first_outcome.rn = 1;
