-- =============================================================================
-- cohorts/target_surgery.sql
-- TARGET / EXPOSURE COHORT — parameterized template
--
-- DO NOT EDIT THIS FILE directly. Set all study-specific values in
-- study_params.yaml under the "target:" section. Parameters are injected
-- at runtime by R/cohorts.R via SqlRender.
--
-- PARAMETERS (all injected from study_params.yaml via R/cohorts.R):
--   @cdm_database_schema      CDM schema (config$cdm_schema)
--   @target_database_schema   Results schema prefix (config$results_schema)
--   @target_cohort_table      Cohort table name (config$cohort_table)
--   @target_cohort_id         Cohort definition ID (target.cohort_id)
--   @study_start_date         Study start date (study_start_date)
--   @study_end_date           Study end date (study_end_date)
--   @visit_concept_ids        OMOP visit_concept_id filter (target.visit_concept_ids)
--                             Empty string = no filter (all visit types included)
--   @min_age                  Minimum age at index in years (target.min_age_at_index)
--                             0 = no age filter
--   @index_concept_ids        Ancestor concept IDs for the index event procedure/condition/drug
--                             (target.index_event.ancestor_concept_ids)
--   @washout_concept_ids      Ancestor concept IDs for prior-outcome washout exclusion
--                             (target.washout.ancestor_concept_ids)
--                             Empty string = no washout block
--   @washout_lookback_days    Days before index to check for prior washout events
--                             (target.washout.lookback_days)
--
-- COHORT LOGIC:
--   INDEX EVENT  : qualifying inpatient visit (or configured visit type) during
--                  which the index procedure occurred, within the study window.
--   INDEX DATE   : visit_start_date of the qualifying visit.
--   COHORT EXIT  : visit_end_date of the qualifying visit (or index + 1 day if null).
--   ONE ENTRY    : first qualifying visit per person (new-user / incident design).
--   EXCLUSIONS   : patients younger than min_age; patients with a prior washout
--                  condition in the lookback window before index.
-- =============================================================================

-- Guard: fires when index concept IDs still contain the placeholder value 0.
-- The R layer (R/cohorts.R) validates concept IDs before this SQL runs, but
-- this guard catches direct SQL execution that bypasses the R pipeline.
{@index_concept_ids == "0"} ? {
  RAISERROR(
    'SETUP REQUIRED - target_surgery.sql: index_concept_ids = 0 placeholder '
    'has not been replaced. Set target.index_event.ancestor_concept_ids in '
    'study_params.yaml and re-run. Use /concept-lookup to find verified concept IDs.',
    16, 1
  );
  RETURN;
}

-- Guard: fires when washout is enabled but concept IDs still contain placeholder 0.
{@washout_concept_ids == "0"} ? {
  RAISERROR(
    'SETUP REQUIRED - target_surgery.sql: washout_concept_ids = 0 placeholder '
    'has not been replaced. Set target.washout.ancestor_concept_ids in '
    'study_params.yaml, or set it to [] to disable washout entirely.',
    16, 1
  );
  RETURN;
}

DELETE FROM @target_database_schema.@target_cohort_table
WHERE cohort_definition_id = @target_cohort_id;

INSERT INTO @target_database_schema.@target_cohort_table (
  cohort_definition_id,
  subject_id,
  cohort_start_date,
  cohort_end_date
)
SELECT
  @target_cohort_id                  AS cohort_definition_id,
  qualifying_event.person_id         AS subject_id,
  qualifying_event.index_date        AS cohort_start_date,
  qualifying_event.cohort_end_date   AS cohort_end_date
FROM (
  SELECT
    vo.person_id,
    CAST(vo.visit_start_date AS DATE) AS index_date,
    CAST(
      ISNULL(vo.visit_end_date, DATEADD(DAY, 1, vo.visit_start_date))
      AS DATE
    ) AS cohort_end_date,
    -- Keep first qualifying visit per person (incident / new-user design).
    -- To keep the most recent event change ASC to DESC.
    -- To allow multiple entries per person remove the ROW_NUMBER filter below.
    ROW_NUMBER() OVER (
      PARTITION BY vo.person_id
      ORDER BY vo.visit_start_date ASC
    ) AS rn

  FROM @cdm_database_schema.visit_occurrence  vo
  INNER JOIN @cdm_database_schema.person       p
    ON p.person_id = vo.person_id

  WHERE
    1 = 1    -- anchor: all clauses below start with AND and can be omitted safely

    -- Visit type filter: set target.visit_concept_ids in study_params.yaml.
    -- 9201 = Inpatient | 9202 = Outpatient | 9203 = Emergency Room.
    -- Set to [] in study_params.yaml to include all visit types.
    {@visit_concept_ids != ""} ? {
    AND vo.visit_concept_id IN (@visit_concept_ids)
    }

    -- Study date window: driven by study_start_date / study_end_date in study_params.yaml.
    AND vo.visit_start_date >= CAST('@study_start_date' AS DATE)
    AND vo.visit_start_date <= CAST('@study_end_date'   AS DATE)

    -- Age filter: set target.min_age_at_index in study_params.yaml.
    -- Set to 0 in study_params.yaml to disable.
    {@min_age != "0"} ? {
    AND DATEDIFF(
          YEAR,
          DATEFROMPARTS(
            p.year_of_birth,
            ISNULL(p.month_of_birth, 7),
            ISNULL(p.day_of_birth,   1)
          ),
          vo.visit_start_date
        ) >= @min_age
    }

    -- Index event filter: the qualifying exposure procedure / condition / drug.
    -- Concept IDs set via target.index_event.ancestor_concept_ids in study_params.yaml.
    -- All descendants are captured via concept_ancestor rollup.
    AND EXISTS (
      SELECT 1
      FROM @cdm_database_schema.procedure_occurrence po
      INNER JOIN @cdm_database_schema.concept_ancestor ca
        ON ca.descendant_concept_id = po.procedure_concept_id
      WHERE ca.ancestor_concept_id IN (@index_concept_ids)
        AND po.person_id      = vo.person_id
        AND po.procedure_date BETWEEN vo.visit_start_date
                                  AND ISNULL(vo.visit_end_date, vo.visit_start_date)
    )

    -- Washout / prior-outcome exclusion: set target.washout in study_params.yaml.
    -- Patients with this condition in the lookback window before index are excluded.
    -- Set target.washout.ancestor_concept_ids to [] in study_params.yaml to disable.
    {@washout_concept_ids != ""} ? {
    AND NOT EXISTS (
      SELECT 1
      FROM @cdm_database_schema.condition_occurrence  prior_event
      INNER JOIN @cdm_database_schema.concept_ancestor ca
        ON ca.descendant_concept_id = prior_event.condition_concept_id
      WHERE
        ca.ancestor_concept_id IN (@washout_concept_ids)
        AND prior_event.person_id = vo.person_id
        AND prior_event.condition_start_date
              BETWEEN DATEADD(DAY, -@washout_lookback_days, vo.visit_start_date)
                  AND DATEADD(DAY,   -1, vo.visit_start_date)
    )
    }

) qualifying_event
WHERE qualifying_event.rn = 1;
