setwd("C:/Users/rapiduser/pad-oler-ssi-val")
source("renv/activate.R")
source("config.R")
source("R/drivers.R")
source("R/connection.R")
configure_java(get_validation_config())
library(DatabaseConnector)
library(SqlRender)
config <- get_validation_config()
conn <- DatabaseConnector::connect(build_connection_details(config))
on.exit(DatabaseConnector::disconnect(conn))
qs <- function(sql) { DatabaseConnector::querySql(conn, SqlRender::translate(SqlRender::render(sql, cdm = config$cdm_schema), targetDialect = "sql server")) }
message("Date range all visits:")
print(qs("SELECT MIN(visit_start_date) AS min_date, MAX(visit_start_date) AS max_date FROM @cdm.visit_occurrence"))
message("Date range inpatient (9201):")
print(qs("SELECT MIN(visit_start_date) AS min_date, MAX(visit_start_date) AS max_date FROM @cdm.visit_occurrence WHERE visit_concept_id = 9201"))