#!/usr/bin/env Rscript
# =============================================================================
# scripts/generate_checklist_step_index.R
#
# Generates the Canonical Step Index block in CHECKLIST.md from
# ../docs/workflow_steps.yaml (workspace mode) or docs/workflow_steps.yaml (standalone mode).
#
# Usage:
#   Rscript scripts/generate_checklist_step_index.R
#   Rscript scripts/generate_checklist_step_index.R --check
# =============================================================================

args <- commandArgs(trailingOnly = TRUE)
check_only <- "--check" %in% args

parse_step_map <- function(path) {
  if (!file.exists(path)) {
    stop("Step map not found: ", path)
  }

  lines <- readLines(path, warn = FALSE)
  idx <- grep("^\\s*-\\s*step:\\s*[0-9]+\\s*$", lines, perl = TRUE)
  if (length(idx) == 0) {
    stop("No step entries found in step map.")
  }

  rows <- lapply(seq_along(idx), function(i) {
    start <- idx[i]
    end <- if (i < length(idx)) idx[i + 1] - 1 else length(lines)
    block <- lines[start:end]

    step_line <- block[grep("^\\s*-\\s*step:\\s*[0-9]+\\s*$", block, perl = TRUE)][1]
    title_line <- block[grep("^\\s*title:\\s*.+$", block, perl = TRUE)][1]
    anchor_line <- block[grep("^\\s*anchor:\\s*.+$", block, perl = TRUE)][1]

    step <- as.integer(sub("^\\s*-\\s*step:\\s*([0-9]+)\\s*$", "\\1", step_line, perl = TRUE))
    title <- trimws(sub("^\\s*title:\\s*(.+)$", "\\1", title_line, perl = TRUE))
    anchor <- trimws(sub("^\\s*anchor:\\s*(.+)$", "\\1", anchor_line, perl = TRUE))

    if (is.na(step) || !nzchar(title) || !nzchar(anchor)) {
      stop("Malformed step map entry near line ", start)
    }

    data.frame(step = step, title = title, anchor = anchor, stringsAsFactors = FALSE)
  })

  out <- do.call(rbind, rows)
  out <- out[order(out$step), ]
  rownames(out) <- NULL
  out
}

build_block <- function(steps) {
  lines <- c(
    "<!-- BEGIN:STEP_INDEX -->",
    "<!-- Generated by scripts/generate_checklist_step_index.R. Do not edit manually. -->"
  )

  for (i in seq_len(nrow(steps))) {
    lines <- c(
      lines,
      sprintf(
        "- Step %d: [%s](%s/GETTING_STARTED.md#%s)",
        steps$step[i],
        steps$title[i],
        docs_link_prefix,
        steps$anchor[i]
      )
    )
  }

  c(lines, "<!-- END:STEP_INDEX -->")
}

replace_block <- function(content, block) {
  begin <- grep("^<!-- BEGIN:STEP_INDEX -->$", content)
  end <- grep("^<!-- END:STEP_INDEX -->$", content)

  if (length(begin) != 1 || length(end) != 1 || begin >= end) {
    stop("Could not find a valid STEP_INDEX marker block in CHECKLIST.md")
  }

  pre <- if (begin > 1) content[seq_len(begin - 1)] else character(0)
  post <- if (end < length(content)) content[(end + 1):length(content)] else character(0)

  c(pre, block, post)
}

docs_path <- if (file.exists("../docs/workflow_steps.yaml")) "../docs" else "docs"
docs_link_prefix <- if (docs_path == "../docs") "../docs" else "docs"

step_map_path <- file.path(docs_path, "workflow_steps.yaml")
checklist_path <- "CHECKLIST.md"

steps <- parse_step_map(step_map_path)
block <- build_block(steps)

if (!file.exists(checklist_path)) {
  stop("Checklist file not found: ", checklist_path)
}

current <- readLines(checklist_path, warn = FALSE)
updated <- replace_block(current, block)

if (check_only) {
  if (!identical(current, updated)) {
    message("CHECKLIST step index is out of date. Run:")
    message("  Rscript scripts/generate_checklist_step_index.R")
    quit(status = 1)
  }
  message("CHECKLIST step index is synchronized.")
  quit(status = 0)
}

writeLines(updated, checklist_path)
message("Updated CHECKLIST step index from ", step_map_path)
