#!/usr/bin/env Rscript
# =============================================================================
# scripts/validate_docs_commands.R
#
# Validates documentation governance rules:
# 1) Command/path references and known deprecated patterns
# 2) Markdown local links and heading anchors
# 3) Step-map consistency for GETTING_STARTED and CHECKLIST
# 4) Heading duplication checks
# 5) Topic ownership checks (warning by default, error in strict mode)
# 6) Generated checklist step index synchronization
#
# Strict mode:
#   DOCS_STRICT=1 Rscript scripts/validate_docs_commands.R
# =============================================================================

args_full <- commandArgs(trailingOnly = FALSE)
file_arg <- grep("^--file=", args_full, value = TRUE)
if (length(file_arg) > 0) {
	script_dir <- dirname(normalizePath(sub("^--file=", "", file_arg[1]), winslash = "/"))
	proj_root <- dirname(script_dir)
} else {
	proj_root <- getwd()
}
setwd(proj_root)

strict_mode <- tolower(Sys.getenv("DOCS_STRICT", unset = "0")) %in% c("1", "true", "yes")
docs_path <- if (dir.exists("../docs")) "../docs" else "docs"
docs_link_prefix <- if (docs_path == "../docs") "../docs" else "docs"
docs_readme_path <- file.path(docs_path, "README.md")

collect_docs <- function() {
		docs <- c(
		"README.md",
		"CHECKLIST.md",
		".github/pull_request_template.md",
		"workflow/README.md",
		"setup/README.md",
		"scripts/README.md",
		"cohorts/README.md",
		"R/README.md",
		"drivers/README.md",
		"tests/README.md",
		"dist/README.md",
			list.files(docs_path, pattern = "\\.md$", full.names = TRUE),
		list.files("scripts", pattern = "README\\.md$", full.names = TRUE, recursive = TRUE)
	)
	unique(docs[file.exists(docs)])
}

add_entry <- function(entries, path, line_no, message) {
	c(entries, sprintf("%s:%d: %s", path, line_no, message))
}

escape_regex <- function(x) {
	gsub("([][{}()+*^$.|?\\\\])", "\\\\\\\\\\1", x)
}

normalize_h2 <- function(line) {
	heading <- trimws(sub("^##\\s+", "", line))
	heading <- tolower(heading)
	heading <- gsub("`", "", heading)
	heading
}

slugify_anchor <- function(text) {
	anchor <- trimws(text)
	anchor <- tolower(anchor)
	anchor <- gsub("`", "", anchor)
	anchor <- gsub("\\[", "", anchor)
	anchor <- gsub("\\]", "", anchor)
	anchor <- gsub("\\(", "", anchor)
	anchor <- gsub("\\)", "", anchor)
	anchor <- gsub("[^a-z0-9 _-]", "", anchor)
	anchor <- gsub("[[:space:]]+", "-", anchor)
	anchor <- gsub("-+", "-", anchor)
	anchor <- gsub("^-|-$", "", anchor)
	anchor
}

build_step_index_block <- function(steps) {
	block <- c(
		"<!-- BEGIN:STEP_INDEX -->",
		"<!-- Generated by scripts/generate_checklist_step_index.R. Do not edit manually. -->"
	)

	for (i in seq_len(nrow(steps))) {
		block <- c(
			block,
			sprintf(
				"- Step %d: [%s](%s/GETTING_STARTED.md#%s)",
				steps$step[i],
				steps$title[i],
				docs_link_prefix,
				steps$anchor[i]
			)
		)
	}

	c(block, "<!-- END:STEP_INDEX -->")
}

extract_anchors <- function(lines) {
	idx <- grep("^#{1,6}\\s+", lines)
	if (length(idx) == 0) {
		return(character(0))
	}

counts <- integer(0)
anchors <- character(0)

for (line in lines[idx]) {
		heading <- sub("^#{1,6}\\s+", "", line)
		heading <- sub("\\s+#+\\s*$", "", heading)
		base <- slugify_anchor(heading)
		if (!nzchar(base)) {
			next
		}

		n <- if (base %in% names(counts)) counts[[base]] + 1L else 1L
		counts[[base]] <- n
		if (n == 1L) {
			anchors <- c(anchors, base)
		} else {
			anchors <- c(anchors, paste0(base, "-", n - 1L))
		}
	}

	anchors
}

parse_step_map <- function(path) {
	if (!file.exists(path)) {
		return(data.frame(step = integer(0), title = character(0), anchor = character(0), stringsAsFactors = FALSE))
	}

	lines <- readLines(path, warn = FALSE)
	idx <- grep("^\\s*-\\s*step:\\s*[0-9]+\\s*$", lines, perl = TRUE)
	if (length(idx) == 0) {
		return(data.frame(step = integer(0), title = character(0), anchor = character(0), stringsAsFactors = FALSE))
	}

	rows <- lapply(seq_along(idx), function(i) {
		start <- idx[i]
		end <- if (i < length(idx)) idx[i + 1] - 1 else length(lines)
		block <- lines[start:end]

		step_line <- block[grep("^\\s*-\\s*step:\\s*[0-9]+\\s*$", block, perl = TRUE)][1]
		title_line <- block[grep("^\\s*title:\\s*.+$", block, perl = TRUE)][1]
		anchor_line <- block[grep("^\\s*anchor:\\s*.+$", block, perl = TRUE)][1]

		step <- as.integer(sub("^\\s*-\\s*step:\\s*([0-9]+)\\s*$", "\\1", step_line, perl = TRUE))
		title <- trimws(sub("^\\s*title:\\s*(.+)$", "\\1", title_line, perl = TRUE))
		anchor <- trimws(sub("^\\s*anchor:\\s*(.+)$", "\\1", anchor_line, perl = TRUE))

		if (is.na(step) || !nzchar(title) || !nzchar(anchor)) {
			return(NULL)
		}

		data.frame(step = step, title = title, anchor = anchor, stringsAsFactors = FALSE)
	})

	rows <- rows[!vapply(rows, is.null, logical(1))]
	if (length(rows) == 0) {
		return(data.frame(step = integer(0), title = character(0), anchor = character(0), stringsAsFactors = FALSE))
	}

	do.call(rbind, rows)
}

split_link_target <- function(target) {
	target <- trimws(target)
	target <- sub("^<", "", target)
	target <- sub(">$", "", target)
	target <- sub("\\s+\"[^\"]*\"$", "", target)

	if (!nzchar(target)) {
		return(list(file = "", anchor = ""))
	}

	if (startsWith(target, "#")) {
		return(list(file = "", anchor = substring(target, 2)))
	}

	hash <- regexpr("#", target, fixed = TRUE)
	if (hash > 0) {
		file <- substr(target, 1, hash - 1)
		anchor <- substr(target, hash + 1, nchar(target))
	} else {
		file <- target
		anchor <- ""
	}

	list(file = utils::URLdecode(file), anchor = utils::URLdecode(anchor))
}

is_external_link <- function(target) {
	grepl("^(https?:|mailto:|tel:)", target, ignore.case = TRUE)
}

resolve_rel_path <- function(source_path, target_file) {
	if (!nzchar(target_file)) {
		return(source_path)
	}

	if (startsWith(target_file, "/")) {
		candidate <- sub("^/", "", target_file)
	} else {
		candidate <- file.path(dirname(source_path), target_file)
	}

	normalizePath(candidate, winslash = "/", mustWork = FALSE)
}

to_repo_relative <- function(path) {
	root_norm <- normalizePath(proj_root, winslash = "/", mustWork = FALSE)
	path_norm <- normalizePath(path, winslash = "/", mustWork = FALSE)
	sub(paste0("^", escape_regex(paste0(root_norm, "/"))), "", path_norm)
}

doc_files <- collect_docs()
issues <- character(0)
warnings <- character(0)

known_bad_patterns <- list(
	list(
		pattern = "workflow/09_create_transportable_bundle\\.R",
		message = "Use workflow/09_build_portable_analysis_bundle.sh or .ps1 instead."
	),
	list(
		pattern = "Rscript\\s+workflow/04_generate_synthea_csv\\.(sh|ps1)",
		message = "Use bash for .sh and powershell -File for .ps1."
	),
	list(
		pattern = "setup/setup_omop_vocab_schema\\.R",
		message = "Use Rscript infrastructure/scripts/setup_omop_vocab_schema.R --study-dir synthea-omop-template (run from workspace root OMOP_Dev/)."
	)
)

required_refs <- list(
		list(path = "README.md", pattern = paste0(escape_regex(docs_link_prefix), "/COMMANDS\\.md"), message = "Link to canonical COMMANDS.md index."),
		list(path = "CHECKLIST.md", pattern = paste0(escape_regex(docs_link_prefix), "/COMMANDS\\.md"), message = "Link to canonical COMMANDS.md instead of duplicating command tables."),
		list(path = docs_readme_path, pattern = "COMMANDS\\.md", message = "Include COMMANDS.md in docs index."),
		list(path = docs_readme_path, pattern = "MAINTAINER_PLAYBOOK\\.md", message = "Include MAINTAINER_PLAYBOOK.md in docs index."),
		list(path = docs_readme_path, pattern = "TOPIC_OWNERSHIP\\.csv", message = "Include TOPIC_OWNERSHIP.csv in docs index.")
)

path_pattern <- "(workflow/[A-Za-z0-9_./-]+\\.(R|sh|ps1)|scripts/[A-Za-z0-9_./-]+\\.R)"
heading_map <- list()
anchor_cache <- new.env(parent = emptyenv())

get_anchors_for <- function(rel_path) {
	key <- rel_path
	if (exists(key, envir = anchor_cache, inherits = FALSE)) {
		return(get(key, envir = anchor_cache, inherits = FALSE))
	}

	if (!file.exists(rel_path)) {
		assign(key, character(0), envir = anchor_cache)
		return(character(0))
	}

	anchors <- extract_anchors(readLines(rel_path, warn = FALSE))
	assign(key, anchors, envir = anchor_cache)
	anchors
}

for (path in doc_files) {
	lines <- readLines(path, warn = FALSE)

	for (rule in known_bad_patterns) {
		hit_idx <- grep(rule$pattern, lines, perl = TRUE)
		if (length(hit_idx) > 0) {
			for (i in hit_idx) {
				issues <- add_entry(issues, path, i, rule$message)
			}
		}
	}

	refs <- regmatches(lines, gregexpr(path_pattern, lines, perl = TRUE))
	refs <- unique(unlist(refs, use.names = FALSE))
	refs <- refs[nzchar(refs)]

	for (ref in refs) {
		if (!file.exists(ref)) {
			hit_idx <- grep(escape_regex(ref), lines, perl = TRUE)
			line_no <- if (length(hit_idx) > 0) hit_idx[1] else 1
			issues <- add_entry(issues, path, line_no, paste0("Referenced path does not exist: ", ref))
		}
	}

	h2_idx <- grep("^##\\s+", lines)
	if (length(h2_idx) > 0) {
		h2_vals <- vapply(lines[h2_idx], normalize_h2, character(1))
		dup_vals <- unique(h2_vals[duplicated(h2_vals)])
		if (length(dup_vals) > 0) {
			for (dup_val in dup_vals) {
				first_line <- h2_idx[which(h2_vals == dup_val)[1]]
				issues <- add_entry(issues, path, first_line, paste0("Duplicate H2 heading in file: ", dup_val))
			}
		}
		heading_map[[path]] <- data.frame(line = h2_idx, heading = h2_vals, stringsAsFactors = FALSE)
	}

	link_pat <- "\\[[^][]*\\]\\(([^)]+)\\)"
	line_hits <- grep(link_pat, lines, perl = TRUE)
	if (length(line_hits) > 0) {
		for (i in line_hits) {
			raw_links <- regmatches(lines[i], gregexpr(link_pat, lines[i], perl = TRUE))[[1]]
			if (length(raw_links) == 0) {
				next
			}

			targets <- sub("^\\[[^][]*\\]\\(([^)]+)\\)$", "\\1", raw_links, perl = TRUE)
			for (target in targets) {
				if (is_external_link(target)) {
					next
				}

				parsed <- split_link_target(target)
				rel_target <- resolve_rel_path(path, parsed$file)
				rel_target <- to_repo_relative(rel_target)

				if (!file.exists(rel_target)) {
					issues <- add_entry(issues, path, i, paste0("Local markdown link target does not exist: ", target))
					next
				}

				if (nzchar(parsed$anchor)) {
					anchors <- get_anchors_for(rel_target)
					if (!(parsed$anchor %in% anchors)) {
						issues <- add_entry(
							issues,
							path,
							i,
							paste0("Unresolved markdown anchor '#", parsed$anchor, "' in target: ", target)
						)
					}
				}
			}
		}
	}
}

for (req in required_refs) {
	if (file.exists(req$path)) {
		lines <- readLines(req$path, warn = FALSE)
		if (!any(grepl(req$pattern, lines, perl = TRUE))) {
			issues <- add_entry(issues, req$path, 1, req$message)
		}
	}
}

top_docs <- intersect(c("README.md", docs_readme_path, "CHECKLIST.md"), names(heading_map))
if (length(top_docs) > 1) {
	all_top <- do.call(rbind, lapply(top_docs, function(path) {
		data.frame(path = path, heading = heading_map[[path]]$heading, line = heading_map[[path]]$line, stringsAsFactors = FALSE)
	}))

	allow_cross_file <- c("scope")
	repeated <- unique(all_top$heading)
	repeated <- repeated[vapply(repeated, function(h) length(unique(all_top$path[all_top$heading == h])) > 1, logical(1))]
	repeated <- repeated[!(repeated %in% allow_cross_file)]
	repeated <- repeated[!grepl("^phase\\s+[0-9]+:", repeated)]

	if (length(repeated) > 0) {
		for (heading in repeated) {
			hit <- all_top[all_top$heading == heading, , drop = FALSE][1, ]
			issues <- add_entry(issues, hit$path, hit$line, paste0("H2 heading reused across top docs: ", heading))
		}
	}
}

step_map_path <- file.path(docs_path, "workflow_steps.yaml")
steps <- parse_step_map(step_map_path)

if (nrow(steps) == 0) {
	issues <- add_entry(issues, step_map_path, 1, "Step map is missing or malformed.")
} else {
	steps <- steps[order(steps$step), ]
	expected <- seq_len(nrow(steps))
	if (!identical(steps$step, expected)) {
		issues <- add_entry(issues, step_map_path, 1, "Step numbers must be sequential starting at 1.")
	}

	gs_path <- file.path(docs_path, "GETTING_STARTED.md")
	if (file.exists(gs_path)) {
		gs_lines <- readLines(gs_path, warn = FALSE)
		gs_idx <- grep("^## Step [0-9]+:", gs_lines)

		if (length(gs_idx) != nrow(steps)) {
			issues <- add_entry(
				issues,
				gs_path,
				if (length(gs_idx) > 0) gs_idx[1] else 1,
				paste0("Step heading count (", length(gs_idx), ") does not match step map (", nrow(steps), ").")
			)
		}

		parsed <- lapply(gs_lines[gs_idx], function(x) {
			m <- regexec("^## Step ([0-9]+):\\s*(.+)$", x, perl = TRUE)
			parts <- regmatches(x, m)[[1]]
			if (length(parts) != 3) {
				return(NULL)
			}
			step_num <- as.integer(parts[2])
			title_full <- trimws(parts[3])
			title_core <- trimws(sub("\\s*\\(.*$", "", title_full))
			list(step = step_num, title = title_core)
		})

		parsed <- parsed[!vapply(parsed, is.null, logical(1))]
		if (length(parsed) == nrow(steps)) {
			for (i in seq_len(nrow(steps))) {
				if (parsed[[i]]$step != steps$step[i] || parsed[[i]]$title != steps$title[i]) {
					issues <- add_entry(
						issues,
						gs_path,
						gs_idx[i],
						paste0("Step heading mismatch for step ", steps$step[i], ": expected '", steps$title[i], "'.")
					)
				}
			}
		}
	}

	checklist_path <- "CHECKLIST.md"
	if (file.exists(checklist_path)) {
		cl_lines <- readLines(checklist_path, warn = FALSE)
		for (i in seq_len(nrow(steps))) {
			pattern <- paste0("Step\\s+", steps$step[i], "(\\b|\\.)")
			if (!any(grepl(pattern, cl_lines, perl = TRUE))) {
				issues <- add_entry(issues, checklist_path, 1, paste0("Checklist is missing a reference to Step ", steps$step[i], "."))
			}
		}
	}
}

ownership_path <- file.path(docs_path, "TOPIC_OWNERSHIP.csv")
if (file.exists(ownership_path)) {
	ownership <- tryCatch(
		read.csv(ownership_path, stringsAsFactors = FALSE),
		error = function(e) NULL
	)

	if (is.null(ownership) || nrow(ownership) == 0) {
		issues <- add_entry(issues, ownership_path, 1, "Topic ownership matrix is unreadable or empty.")
	} else {
		required_cols <- c("topic", "owner_file", "heading_regex", "severity")
		if (!all(required_cols %in% names(ownership))) {
			issues <- add_entry(issues, ownership_path, 1, "Topic ownership matrix is missing required columns.")
		} else {
			md_files <- doc_files
			for (i in seq_len(nrow(ownership))) {
				owner <- ownership$owner_file[i]
				if (!file.exists(owner) && docs_path == "../docs" && startsWith(owner, "docs/")) {
					owner <- sub("^docs/", "../docs/", owner)
				}
				regex <- ownership$heading_regex[i]
				severity <- tolower(ownership$severity[i])

				if (!file.exists(owner)) {
					issues <- add_entry(issues, ownership_path, i + 1, paste0("Owner file does not exist: ", owner))
					next
				}

				for (doc in md_files[md_files != owner]) {
					lines <- readLines(doc, warn = FALSE)
					heading_idx <- grep("^#{1,6}\\s+", lines)
					if (length(heading_idx) == 0) {
						next
					}

					matches <- heading_idx[grepl(regex, lines[heading_idx], perl = TRUE)]
					if (length(matches) > 0) {
						msg <- paste0(
							"Topic '",
							ownership$topic[i],
							"' heading appears outside owner file ",
							owner,
							"."
						)

						if (strict_mode || identical(severity, "error")) {
							issues <- add_entry(issues, doc, matches[1], msg)
						} else {
							warnings <- add_entry(warnings, doc, matches[1], msg)
						}
					}
				}
			}
		}
	}
}

if (nrow(steps) > 0 && file.exists("CHECKLIST.md")) {
	checklist_lines <- readLines("CHECKLIST.md", warn = FALSE)
	begin_idx <- grep("^<!-- BEGIN:STEP_INDEX -->$", checklist_lines)
	end_idx <- grep("^<!-- END:STEP_INDEX -->$", checklist_lines)

	if (length(begin_idx) != 1 || length(end_idx) != 1 || begin_idx >= end_idx) {
		issues <- add_entry(issues, "CHECKLIST.md", 1, "STEP_INDEX marker block is missing or malformed.")
	} else {
		expected_block <- build_step_index_block(steps)
		current_block <- checklist_lines[begin_idx:end_idx]
		if (!identical(current_block, expected_block)) {
			issues <- add_entry(
				issues,
				"CHECKLIST.md",
				begin_idx,
				"Canonical step index is out of date. Run scripts/generate_checklist_step_index.R."
			)
		}
	}
}

if (length(warnings) > 0) {
	cat("Documentation warnings:\n\n")
	cat(paste0("- ", warnings, collapse = "\n"), "\n\n")
}

if (length(issues) > 0) {
	cat("Documentation command/path validation FAILED:\n\n")
	cat(paste0("- ", issues, collapse = "\n"), "\n")
	quit(status = 1)
}

cat("Documentation command/path validation passed.\n")
